version: "2"
services:
  php:
    container_name: php
    build: ./.docker/php
    environment:
      TZ: America/Fortaleza
    volumes:
      - ./application:/var/www/html
    networks:
      - default
  db:
    container_name: desafio_db
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password_desafio
      MYSQL_DATABASE: desafio
      MYSQL_USER: userdesafio
      MYSQL_PASSWORD: password_desafio
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default
  web:
    container_name: web
    image: "nginx:1.13.8-alpine"
    volumes:
      - ./application:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/logs:/var/log/nginx/
      - ./.docker/nginx/cert:/app/cert/
    ports:
      - "8000:80"
    links:
      - "php"
      - "db"

networks:
  default:
